2025-01-07 18:53:20.147 | INFO     | __main__:start_auth:41 - Получены данные для авторизации: {'accountName': '1', 'phoneNumber': '79621972011', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'Mi 13 Ultra', 'systemVersion': 'Ubuntu 22.04 LTS'}
2025-01-07 18:53:20.151 | INFO     | app:auth_account:282 - Начало авторизации для номера: +79621972011
2025-01-07 18:53:20.152 | INFO     | app:auth_account:298 - Создание клиента с конфигурацией: {'name': 'session_79621972011', 'api_id': 20902632, 'api_hash': '9a1d8b31c0041f760ef748910c793f16', 'device_model': 'Mi 13 Ultra', 'system_version': 'Ubuntu 22.04 LTS', 'app_version': '1.0', 'in_memory': True}
2025-01-07 18:53:24.126 | ERROR    | app:auth_account:336 - Ошибка в auth_account: required argument is not an integer
2025-01-07 18:53:24.128 | INFO     | __main__:start_auth:53 - Результат авторизации: {'success': False, 'error': 'required argument is not an integer'}
2025-01-08 00:59:38.502 | INFO     | __main__:start_auth:41 - Получены данные для авторизации: {'accountName': '12333', 'phoneNumber': '789789766', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random'}
2025-01-10 16:40:55.434 | INFO     | __main__:start_auth:33 - Получены данные для авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random'}
2025-01-10 16:50:36.352 | INFO     | __main__:start_auth:33 - Получены данные для авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111'}
2025-01-10 16:50:39.986 | ERROR    | app:auth_account:299 - Ошибка в auth_account: [Errno 2] No such file or directory: 'accounts\\111\\admin\\79621972011\\79621972011.json'
2025-01-10 16:57:48.820 | INFO     | __main__:start_auth:41 - Получены данные для авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111'}
2025-01-10 16:58:21.504 | INFO     | __main__:finish_auth:74 - Получены данные для завершения авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111', 'code': '17110', 'phoneHash': '7a7f98e86597ed9564'}
2025-01-10 16:58:21.507 | ERROR    | app:complete_auth:168 - Ошибка в complete_auth: [Errno 2] No such file or directory: 'accounts/admin/79621972011.json'
2025-01-10 16:59:49.604 | INFO     | __main__:start_auth:41 - Получены данные для авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111'}
2025-01-10 17:00:03.717 | INFO     | __main__:finish_auth:74 - Получены данные для завершения авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111', 'code': '20353', 'phoneHash': 'f8f7421c70d8fbdbb4'}
2025-01-10 17:00:03.720 | ERROR    | app:complete_auth:168 - Ошибка в complete_auth: [Errno 2] No such file or directory: 'accounts/admin/79621972011.json'
2025-01-10 17:02:23.121 | INFO     | __main__:start_auth:41 - Получены данные для авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111'}
2025-01-10 17:03:40.134 | INFO     | __main__:finish_auth:74 - Получены данные для завершения авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111', 'code': '66569', 'phoneHash': '527d6ab6297e40501c'}
2025-01-10 17:03:40.136 | ERROR    | app:complete_auth:168 - Ошибка в complete_auth: [Errno 2] No such file or directory: 'accounts/admin/79621972011.json'
2025-01-10 17:07:54.524 | INFO     | __main__:start_auth:41 - Получены данные для авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin_acc', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111'}
2025-01-10 17:08:10.222 | INFO     | __main__:finish_auth:74 - Получены данные для завершения авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin_acc', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111', 'code': '91080', 'phoneHash': 'c8e7acdce6b88a47e6'}
2025-01-10 17:08:10.225 | ERROR    | app:complete_auth:168 - Ошибка в complete_auth: [Errno 2] No such file or directory: 'accounts/admin_acc/79621972011.json'
2025-01-10 17:58:01.812 | INFO     | __main__:start_auth:44 - Получены данные для авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin_acc', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111'}
2025-01-10 17:58:24.506 | INFO     | __main__:finish_auth:77 - Получены данные для завершения авторизации: {'accountName': 'owner', 'phoneNumber': '79621972011', 'password': 'HUR97qVypS', 'proxyUrl': '', 'accountType': 'admin_acc', 'deviceModel': 'random', 'systemVersion': 'random', 'groupName': '111', 'code': '50853', 'phoneHash': 'f122daf11466349c4b'}
2025-01-10 17:58:24.509 | ERROR    | app:complete_auth:171 - Ошибка в complete_auth: [Errno 2] No such file or directory: 'accounts/admin_acc/79621972011.json'
